os: Visual Studio 2015 CTP

platform:
  - Any CPU

configuration:
  - Release

install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - ps: Invoke-WebRequest "https://stylecop.codeplex.com/downloads/get/323236" -OutFile "StyleCopInstaller.msi"
  - ps: Start-Process .\StyleCopInstaller.msi /quiet -Wait

before_build:
  - nuget restore